# Generated by Django 3.1.6 on 2021-02-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('name', models.CharField(max_length=10, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
