# Generated by Django 3.1.7 on 2021-02-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holy', '0005_auto_20210228_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_arrival',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='holy.category'),
        ),
    ]
