# Generated by Django 3.1.7 on 2021-02-27 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holy', '0007_remove_new_arrival_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CATEGORY',
            new_name='CATE_GORY',
        ),
        migrations.AddField(
            model_name='new_arrival',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='holy.cate_gory'),
        ),
    ]
