# Generated by Django 3.1.7 on 2021-03-13 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holy', '0010_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('country', models.CharField(max_length=10)),
                ('add1', models.TextField(max_length=50)),
                ('add2', models.TextField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
