# Generated by Django 3.1.7 on 2021-03-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holy', '0012_auto_20210314_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_place',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
