# Generated by Django 3.1.7 on 2021-03-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holy', '0014_auto_20210314_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_place',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holy.new_arrival'),
        ),
    ]
